
export const BRAND_SWAP_CONTRACT = process.env.REACT_APP_BRANDSWAP_ADDRESS;
export const SELLING_CONTRACT = process.env.REACT_APP_SELLING_ADDRESS;
export const ERC_20_TOKEN_CONTRACT = process.env.REACT_APP_ERC20_ADDRESS;
export const OWNER_ADDRESS = process.env.REACT_APP_BRANDSWAP_MINT_ADDRESS;
export const POLYGON_SCAN_ADDRESS = process.env.REACT_APP_POLYGON_SCAN_ADDRESS;